name: Pigweed runner

on:
  push:
    branches: [ master ]

jobs:
  run-python-on-selfhosted:
    runs-on: self-hosted 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build changes
        run: |
          cd ~/runner_build/pico-sdk-pigweed
          git pull
          rm -rf build 
          mkdir build 
          cd build 
          cmake .. -DPICO_BOARD=pigweed_dut -DPICO_SDK_PATH=~/pico/pico-sdk
          cd test
          make -j4
          
      - name: Run Python script
        run: |
          cd ~/pigweed_tests
          git pull
          python3 ~/pigweed_tests/auto-tester.py --dut ttyACM0 --buddy ttyACM1 --tests xxx/xxx.json

      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pigweed-test-results
          path: /home/louis/pigweed_tests/results.json
